spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:scheduler_application;
    username: scheduler
    password: scheduler
  flyway:
    user: scheduler
    password: scheduler
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  quartz:
    jdbc:
      initialize-schema: always