spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
  quartz:
    jdbc:
      initialize-schema: always
uk:
  gov:
    hmcts:
      juror:
        security:
          use-database: true
          token-validity: 1800000
          secret: VGhpc0lzQUR1bW15U2VjcmV0S2V5VGhhdE5vT25lS25vd3NUaGVWYWx1ZXNJdENvbnRhaW5z
          admin-user:
            email: dummy@email.com
            password: password
            firstname: firstname
            lastname: lastname
scheduler:
  security:
    juror-api-service-authentication:
      id: JDCRON001
      issuer: Scheduler Service
      subject: Cron
      token-validity: 1600000
      secret: W3N1cGVyLXNlY3JldC1vbmUtYnVyZWF1XVtzdXBlci1zZWNyZXQtb25lLWJ1cmVhdV1bc3VwZXItc2VjcmV0LW9uZS1idXJlYXVd
    api-job-execution-service-authentication:
      issuer: Scheduler Service
      subject: scheduler@scheduler.cgi.com
      token-validity: 1600000
      secret: VGhpc0lzQUR1bW15U2VjcmV0S2V5VGhhdE5vT25lS25vd3NUaGVWYWx1ZXNJdENvbnRhaW5zQnV0Rm9yVGhlRXhlY3V0aW9uTGF5ZXJUaGlzVGltZQ==