java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    juror:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    ENABLE_FLYWAY: true
    RUN_DB_MIGRATION_ON_STARTUP: true
    DB_HOST: "juror-dev.postgres.database.azure.com"
    DB_NAME: "pr-${CHANGE_ID}-juror-scheduler-api"
    DB_USER_NAME: "hmcts"
    DB_PORT: 5432
  secrets:
    DB_PASSWORD:
      secretRef: "postgres"
      key: PASSWORD
      disabled: false
postgresql:
  enabled: true
  flexibleserver: "juror-dev"
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-juror-scheduler-api"
