name: Template CI

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: "Az CLI login"
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          client-id: 82f79201-9a30-4160-b264-7bbed775c7f4 # DTS Developers GitHub Actions ACR Publisher 3
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true

      - name: 'ACR Login'
        run: |
          az acr login --name hmctsprod

      - name: Build
        run: ./gradlew check
